// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DiscountAttributes     string
	DiscountMetaAttributes string
	DiscountRule           string
}{
	DiscountAttributes:     "discount_attributes",
	DiscountMetaAttributes: "discount_meta_attributes",
	DiscountRule:           "discount_rule",
}
